Repository NREL/OpenOA, pull requests merged in 2022-08, with the labels that each got.

#189 improved compute_shear & added extrapolate_windspeed and test
  .pre-commit-config.yaml
  CHANGELOG.md
  operational_analysis/toolkits/met_data_processing.py
  readme.md
  runtime.txt
  sphinx/requirements.txt
  test/unit/test_met_data_processing_toolkit.py
Labels: enhancement

#194 Add `PlantData.to_csv()`
  examples/00_intro_to_plant_data.ipynb
  openoa/plant.py
  test/__init__.py
  test/regression/plantdata_validations.py
Labels: enhancement, v3

#196 Enhancement: Create tests for the plant module
  openoa/plant.py
  setup.py
  test/unit/test_plant_data.py
Labels: v3

#197 Add the v2 `AssetData` methods to v3 `PlantData`
  openoa/plant.py
Labels: v3
