Repository NREL/OpenOA, pull requests merged in 2024-02, with the labels that each got.

#272 Bug Fix: Pandas loc-chaining
  CHANGELOG.md
  examples/project_ENGIE.py
  openoa/utils/timeseries.py
  test/regression/turbine_long_term_gross_energy.py
  test/regression/wake_losses.py
Labels: bug, maintenance

#268 Enhancement/update rated power in tie
  CHANGELOG.md
  examples/03_turbine_ideal_energy.ipynb
  openoa/analysis/turbine_long_term_gross_energy.py
  openoa/schema/base_electrical_losses_schema.json
  openoa/schema/base_electrical_losses_schema.yml
  openoa/schema/base_monte_carlo_aep_schema.json
  openoa/schema/base_monte_carlo_aep_schema.yml
  openoa/schema/base_tie_schema.json
  openoa/schema/base_tie_schema.yml
  openoa/schema/base_yaw_misalignmental_losses_schema.json
  openoa/schema/base_yaw_misalignmental_losses_schema.yml
  openoa/schema/metadata.py
  openoa/schema/scada_wake_losses_schema.json
  openoa/schema/scada_wake_losses_schema.yml
  openoa/schema/temperature_monte_carlo_aep_schema.json
  openoa/schema/temperature_monte_carlo_aep_schema.yml
  openoa/schema/temperature_wind_direction_monte_carlo_aep_schema.json
  openoa/schema/temperature_wind_direction_monte_carlo_aep_schema.yml
  openoa/schema/tower_wake_losses_schema.json
  openoa/schema/tower_wake_losses_schema.yml
  openoa/schema/wind_direction_monte_carlo_aep_schema.json
  openoa/schema/wind_direction_monte_carlo_aep_schema.yml
  sphinx/examples/03_turbine_ideal_energy.ipynb
  test/regression/plantdata_validations.py
  test/regression/turbine_long_term_gross_energy.py
Labels: enhancement

#266 Enhancement: Reduce Example Runtimes
  examples/02c_augmented_plant_aep_analysis.ipynb
  examples/03_turbine_ideal_energy.ipynb
  examples/05_eya_gap_analysis.ipynb
  setup.py
  sphinx/examples/02c_augmented_plant_aep_analysis.ipynb
  sphinx/examples/03_turbine_ideal_energy.ipynb
  sphinx/examples/05_eya_gap_analysis.ipynb
Labels: enhancement, documentation, analysis-methods

#273 Maintenance: Complete Adoption of `project.toml`
  .gitignore
  pyproject.toml
  setup.py
  test/conftest.py
Labels: maintenance

#274 Maintenance: Upgrade Outdated Python Style
  .pre-commit-config.yaml
  openoa/analysis/aep.py
  openoa/analysis/electrical_losses.py
  openoa/analysis/turbine_long_term_gross_energy.py
  openoa/analysis/wake_losses.py
  openoa/analysis/yaw_misalignment.py
  openoa/logging.py
  openoa/plant.py
  openoa/utils/imputing.py
  openoa/utils/plot.py
  openoa/utils/qa.py
Labels: bug, enhancement
